services:
  mssql-database:
    image: mcr.microsoft.com/mssql/server

  apigateway:
    image: saifdev22/apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

  identity.api:
    image: saifdev22/identityapi
    build:
      context: .
      dockerfile: Services/Identity/Identity.API/Dockerfile

  # blazor.wasm:
  #   image: ${DOCKER_REGISTRY-}blazorwasm
  #   build:
  #     context: Clients/Clients.BlazorWASM
  #     dockerfile: Clients/Clients.BlazorWASM/Dockerfile

  blazor.server:
    image: saifdev22/blazor-app

    build:
      context: .
      dockerfile: Clients/BlazorWasmHosted/Blazor.Server/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_HTTP_PORTS=8080
        - ASPNETCORE_HTTPS_PORTS=8081
    ports:
        - 7001:8080
        - 7070:8081
  

