name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: src
          file: src/Clients/BlazorWasmHosted/Blazor.Server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blazor-app:latest, ${{ secrets.DOCKERHUB_USERNAME }}/blazor-app:${{ github.run_number }} 

  update_server:
      name: Deploy to Server
      runs-on: ubuntu-latest
      needs: build_images
      steps:

        - name: Replacing container
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_KEY }}
            script: |
              docker image pull ${{ secrets.DOCKERHUB_USERNAME }}/blazor-app:latest
              docker container stop blazor-v1 || true
              docker container prune -f || true
              docker run -d --name blazor-v1 --restart unless-stopped -p 32775:8080 ${{ secrets.DOCKERHUB_USERNAME }}/blazor-app:latest
              docker image prune -f
      
