name: Docker Image CI

on:
  push:
    branches: [ "test-branch" ]
  pull_request:
    branches: [ "test-branch" ]

jobs:
  copy_files:
      name: Copy files to server
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - name: copy file via ssh password
          uses: appleboy/scp-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            password: ${{ secrets.SSH_KEY }}
            source: src/docker-compose.yml
            target: /home/github-actions
